#!/bin/bash

for file in $(ls -p | grep -v /);
do
   if [[ "$(ls -A)" && "$(ls -A)" != "hunter" ]]; then
   echo "The file name is $file "
      grep -m1 "" $file
      if [[ "$(grep -n $1 $file)" ]]; then
         grep -n $1 $file
      else
         echo "String not found"
      fi
   echo " "
   else
      echo "The directory is empty"
   fi
done
